# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=150, verbose_name='danie')),
                ('price', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='cena')),
            ],
            options={
                'verbose_name': 'danie',
                'verbose_name_plural': 'dania',
            },
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_drinks', models.CharField(max_length=64, verbose_name='bezlakoholowe')),
                ('drinks', models.CharField(max_length=64, verbose_name='drinki')),
                ('wines', models.CharField(max_length=64, verbose_name='wina')),
                ('beer', models.CharField(max_length=64, verbose_name='piwo')),
                ('juice', models.CharField(max_length=64, verbose_name='soki')),
            ],
            options={
                'verbose_name': 'napój',
                'verbose_name_plural': 'napoje',
            },
        ),
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingridient_name', models.CharField(max_length=64, verbose_name='składnik')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Dish', verbose_name='danie')),
            ],
            options={
                'verbose_name': 'składnik',
                'verbose_name_plural': 'składniki',
            },
        ),
    ]
