# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='cena'),
        ),
    ]
