# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_drinks_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='beer',
            field=models.CharField(max_length=64, null=True, verbose_name='piwo'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='drinks',
            field=models.CharField(max_length=64, null=True, verbose_name='drinki'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='juice',
            field=models.CharField(max_length=64, null=True, verbose_name='soki'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='soft_drinks',
            field=models.CharField(max_length=64, null=True, verbose_name='bezlakoholowe'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='wines',
            field=models.CharField(max_length=64, null=True, verbose_name='wina'),
        ),
    ]
