# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20170905_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='soft_drinks',
            field=models.CharField(max_length=64, null=True, verbose_name='bezalkoholowe'),
        ),
    ]
