# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20170905_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingridient',
            name='id',
        ),
        migrations.AlterField(
            model_name='ingridient',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.Dish', verbose_name='danie'),
        ),
    ]
