# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20170905_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='beer',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='juice',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='soft_drinks',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='wines',
        ),
        migrations.AlterField(
            model_name='drinks',
            name='drinks',
            field=models.IntegerField(choices=[(1, 'soft_drinks'), (2, 'drinks'), (3, 'wines'), (4, 'beer'), (5, 'juice')], null=True, verbose_name='napoje'),
        ),
    ]
