# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20170906_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='drinks',
        ),
        migrations.AddField(
            model_name='drinks',
            name='drink_name',
            field=models.CharField(max_length=99, null=True, verbose_name='napoje nazwa'),
        ),
        migrations.AddField(
            model_name='drinks',
            name='drink_type',
            field=models.IntegerField(choices=[(1, 'soft_drinks'), (2, 'drinks'), (3, 'wines'), (4, 'beer'), (5, 'juice')], null=True, verbose_name='napoje typ'),
        ),
    ]
