# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20170906_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='drink_volume',
            field=models.IntegerField(choices=[(1, 'by the glass'), (2, 'bottle'), (3, 'decanter'), (4, 'beer'), (5, 'juice')], null=True, verbose_name='objętość'),
        ),
        migrations.AddField(
            model_name='drinks',
            name='wine_type',
            field=models.IntegerField(choices=[(1, 'white'), (2, 'rose'), (3, 'red'), (4, 'dry'), (5, 'sweet'), (6, 'semi-sweet'), (6, 'semi-dry')], null=True, verbose_name='typy win'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='cena'),
        ),
    ]
