# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20170906_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='wine_type',
        ),
        migrations.AddField(
            model_name='drinks',
            name='wine_colors',
            field=models.IntegerField(choices=[(1, 'white'), (2, 'rose'), (3, 'red')], null=True, verbose_name='kolor wina'),
        ),
        migrations.AddField(
            model_name='drinks',
            name='wine_sweetness',
            field=models.IntegerField(choices=[(1, 'dry'), (2, 'sweet'), (3, 'semi-sweet'), (4, 'semi-dry')], null=True, verbose_name='smak wina'),
        ),
    ]
